export const USERS = [
  {
    id: 1,
    name: "Leanne Graham",
    username: "Bret",
    email: "Sincere@april.biz",
    address: {
      street: "Kulas Light",
      suite: "Apt. 556",
      city: "Gwenborough",
      zipcode: "92998-3874",
      geo: { lat: "-37.3159", lng: "81.1496" },
    },
    phone: "1-770-736-8031 x56442",
    website: "hildegard.org",
    company: {
      name: "Romaguera-Crona",
      catchPhrase: "Multi-layered client-server neural-net",
      bs: "harness real-time e-markets",
    },
  },
  {
    id: 2,
    name: "Ervin Howell",
    username: "Antonette",
    email: "Shanna@melissa.tv",
    address: {
      street: "Victor Plains",
      suite: "Suite 879",
      city: "Wisokyburgh",
      zipcode: "90566-7771",
      geo: { lat: "-43.9509", lng: "-34.4618" },
    },
    phone: "010-692-6593 x09125",
    website: "anastasia.net",
    company: {
      name: "Deckow-Crist",
      catchPhrase: "Proactive didactic contingency",
      bs: "synergize scalable supply-chains",
    },
  },
  {
    id: 3,
    name: "Clementine Bauch",
    username: "Samantha",
    email: "Nathan@yesenia.net",
    address: {
      street: "Douglas Extension",
      suite: "Suite 847",
      city: "McKenziehaven",
      zipcode: "59590-4157",
      geo: { lat: "-68.6102", lng: "-47.0653" },
    },
    phone: "1-463-123-4447",
    website: "ramiro.info",
    company: {
      name: "Romaguera-Jacobson",
      catchPhrase: "Face to face bifurcated interface",
      bs: "e-enable strategic applications",
    },
  },
  {
    id: 4,
    name: "Patricia Lebsack",
    username: "Karianne",
    email: "Julianne.OConner@kory.org",
    address: {
      street: "Hoeger Mall",
      suite: "Apt. 692",
      city: "South Elvis",
      zipcode: "53919-4257",
      geo: { lat: "29.4572", lng: "-164.2990" },
    },
    phone: "493-170-9623 x156",
    website: "kale.biz",
    company: {
      name: "Robel-Corkery",
      catchPhrase: "Multi-tiered zero tolerance productivity",
      bs: "transition cutting-edge web services",
    },
  },
  {
    id: 5,
    name: "Chelsey Dietrich",
    username: "Kamren",
    email: "Lucio_Hettinger@annie.ca",
    address: {
      street: "Skiles Walks",
      suite: "Suite 351",
      city: "Roscoeview",
      zipcode: "33263",
      geo: { lat: "-31.8129", lng: "62.5342" },
    },
    phone: "(254)954-1289",
    website: "demarco.info",
    company: {
      name: "Keebler LLC",
      catchPhrase: "User-centric fault-tolerant solution",
      bs: "revolutionize end-to-end systems",
    },
  },

  {
    id: 6,
    name: "Lucas Fernández",
    username: "lucasf",
    email: "lucas.fernandez@mail.com",
    address: {
      street: "Av. Siempre Viva",
      suite: "Depto 12",
      city: "Buenos Aires",
      zipcode: "1001",
      geo: { lat: "-34.6037", lng: "-58.3816" },
    },
    phone: "+54 11 4567-8901",
    website: "lucas.dev",
    company: {
      name: "Pampa Tech",
      catchPhrase: "Innovación constante",
      bs: "cloud platforms",
    },
  },
  {
    id: 7,
    name: "María López",
    username: "marial",
    email: "maria.lopez@mail.com",
    address: {
      street: "Gran Vía",
      suite: "Piso 4",
      city: "Madrid",
      zipcode: "28013",
      geo: { lat: "40.4168", lng: "-3.7038" },
    },
    phone: "+34 600 123 456",
    website: "marialopez.dev",
    company: {
      name: "IberiaSoft",
      catchPhrase: "Software sin fronteras",
      bs: "enterprise solutions",
    },
  },
  {
    id: 8,
    name: "Juan Pérez",
    username: "juanp",
    email: "juan.perez@mail.com",
    address: {
      street: "Insurgentes Sur",
      suite: "Oficina 301",
      city: "CDMX",
      zipcode: "03100",
      geo: { lat: "19.4326", lng: "-99.1332" },
    },
    phone: "+52 55 9876 5432",
    website: "juanp.mx",
    company: {
      name: "Azteca Digital",
      catchPhrase: "Código que escala",
      bs: "web services",
    },
  },
  {
    id: 9,
    name: "Ana Torres",
    username: "anatorres",
    email: "ana.torres@mail.com",
    address: {
      street: "Rua Augusta",
      suite: "Apto 502",
      city: "São Paulo",
      zipcode: "01305-000",
      geo: { lat: "-23.5505", lng: "-46.6333" },
    },
    phone: "+55 11 91234-5678",
    website: "anatorres.dev",
    company: {
      name: "BrasilWare",
      catchPhrase: "Tecnología humana",
      bs: "digital transformation",
    },
  },
  {
    id: 10,
    name: "Carlos Gómez",
    username: "cgomez",
    email: "carlos.gomez@mail.com",
    address: {
      street: "Calle 72",
      suite: "Casa 8",
      city: "Bogotá",
      zipcode: "110221",
      geo: { lat: "4.7110", lng: "-74.0721" },
    },
    phone: "+57 300 456 7890",
    website: "cgomez.co",
    company: {
      name: "Andes Tech",
      catchPhrase: "Impulsando ideas",
      bs: "custom software",
    },
  },

  {
    id: 11,
    name: "Sofía Martínez",
    username: "sofiam",
    email: "sofia.m@mail.com",
    address: {
      street: "Alameda Central",
      suite: "Depto 3",
      city: "Monterrey",
      zipcode: "64000",
      geo: { lat: "25.6866", lng: "-100.3161" },
    },
    phone: "+52 81 1234 5678",
    website: "sofiam.dev",
    company: {
      name: "Nortech",
      catchPhrase: "Código del norte",
      bs: "software solutions",
    },
  },
  {
    id: 12,
    name: "Pedro Silva",
    username: "pedros",
    email: "pedro.s@mail.com",
    address: {
      street: "Av. Paulista",
      suite: "Sala 9",
      city: "São Paulo",
      zipcode: "01310-000",
      geo: { lat: "-23.5617", lng: "-46.6560" },
    },
    phone: "+55 11 99876-1234",
    website: "pedros.dev",
    company: {
      name: "CodeBrasil",
      catchPhrase: "Escalando futuro",
      bs: "saas products",
    },
  },
  {
    id: 13,
    name: "Laura Méndez",
    username: "lauram",
    email: "laura.m@mail.com",
    address: {
      street: "Calle Mayor",
      suite: "Piso 2",
      city: "Valencia",
      zipcode: "46001",
      geo: { lat: "39.4699", lng: "-0.3763" },
    },
    phone: "+34 611 987 654",
    website: "lauram.dev",
    company: {
      name: "Mediterránea Tech",
      catchPhrase: "Soluciones claras",
      bs: "web platforms",
    },
  },
  {
    id: 14,
    name: "Diego Ramos",
    username: "diegor",
    email: "diego.r@mail.com",
    address: {
      street: "Av. Libertador",
      suite: "Of. 21",
      city: "Santiago",
      zipcode: "8320000",
      geo: { lat: "-33.4489", lng: "-70.6693" },
    },
    phone: "+56 9 8765 4321",
    website: "diegor.dev",
    company: {
      name: "Andes Code",
      catchPhrase: "Código sin límites",
      bs: "enterprise apps",
    },
  },
  {
    id: 15,
    name: "Valentina Ríos",
    username: "valer",
    email: "valentina@mail.com",
    address: {
      street: "Costanera",
      suite: "Depto 5",
      city: "Montevideo",
      zipcode: "11000",
      geo: { lat: "-34.9011", lng: "-56.1645" },
    },
    phone: "+598 99 123 456",
    website: "valer.dev",
    company: {
      name: "RioSoft",
      catchPhrase: "Innovación simple",
      bs: "mobile apps",
    },
  },
];
